######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 2 22:53:53 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += sudoku.h
SOURCES += sudoku.cpp
