######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 4 00:14:42 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += sudoku.h
SOURCES += sudoku.cpp
