######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 3 13:46:02 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += sudoku.h
SOURCES += sudoku.cpp
